### ISSUE TITLE
Error: not_in_channel with slack api client

### ISSUE THREAD

**Issue by cristianbuta** [slackapi/deno-slack-sdk#128]
I'm trying to use the conversations.history method for reading all the messages in a public slack channel.

The bot scopes that I am using are: 
```
[
    "commands",
    "channels:read",
    "channels:history",
    "im:history",
    "mpim:history",
    "groups:history",
    "groups:read",
    "chat:write",
    "chat:write.public",
]
```

The response I am receiving from calling the method is:

```
{
  "ok": false,
  "error": "not_in_channel"
}
```

I managed to fix this issue by manually inviting the bot in the specific channel. But this is not something that I want my bot users to be required to do.

I want to be able to read all the conversations that the user that is initiating the workflow has access to without any other requirements.

How can I do this?

**Comment by filmaj** [comment]
Unfortunately, this is a limitation / requirement of the [`channels:history` scope](https://api.slack.com/scopes/channels:history). This scope, in turn, is required to use the [`conversations.history` API](https://api.slack.com/methods/conversations.history).

Some of our APIs currently are able to get around this channel-membership requirement specifically for applications built on the next-generation platform (the one exception so far is [`chat.postMessage`](https://api.slack.com/methods/chat.postMessage)). I am following up internally to see if we plan to grant a similar exception to e.g. `conversations.history`, and will let you know when I have more information.

**Comment by tomas-zijdemans-vipps** [comment]
I solved this issue by simply having the bot join the channel automatically if needed. This should work:
1. Get the channel using conversations.info
2. Check if you are a member by looking at is_member in the response
3. If not a member, use conversations.join

**Comment by filmaj** [comment]
Going to close this issue out but feel free to re-open if you have further questions in this area.
