### ISSUE TITLE
How do you roll out an app with an Event trigger to multiple channels?

### ISSUE THREAD

**Issue by tomas-zijdemans-vipps** [slackapi/deno-slack-sdk#166]
Hi!

I've created a simple app that has an event trigger for reaction added. Like the sample code: https://github.com/slack-samples/deno-code-snippets/blob/main/Event_Triggers/triggers/reaction_added.ts

To enable it (after deploying it) I had to:
1. Add the app in a channel (Channel settings -> Integrations -> Add an app), and
2. Add that channel's ID to the trigger file:  channel_ids: ["CABC12ABC"] (and use the trigger CLI command to create the trigger)

Now my problem is: The users love the app and want to enable it globally :) (or at least to many of our channels).

I'm stuck on how to scale my app to many channels. Do I need to repeat the steps over **per channel**? (add the app in channel settings, add the channelid to the channel_id array in the trigger file, update the trigger and then update the trigger using the CLI). That would mean that users would have to contact me for every channel they want to add the app in, that would be quite cumbersome. How can this be solved?

**Comment by filmaj** [comment]
Hello @tomas-zijdemans-vipps 👋 

> I'm stuck on how to scale my app to many channels. Do I need to repeat the steps over per channel? (add the app in channel settings, add the channelid to the channel_id array in the trigger file, update the trigger and then update the trigger using the CLI). That would mean that users would have to contact me for every channel they want to add the app in, that would be quite cumbersome. How can this be solved?

This is a great question! And a common one we receive, as it is not very clear at this stage from our education materials how to handle this situation. Let me try to explain the options we have currently settled on.

As you have identified, you could manually and explicitly create a new trigger with a new channel ID to roll it out to every new channel. Along the same lines, you could edit an existing trigger and expand the list of channel IDs in the trigger. Of course, this is tedious! Perhaps this may work if you only need to deal with a few channels, but there is a better - though more advanced - approach to tackling the problem.

The key is the ability to create triggers _dynamically_. That is, you could write a custom function that calls the `workflows.triggers.create` API that we provide. We have some documentation on creating an event trigger at runtime [here](https://api.slack.com/automation/triggers/event#create-trigger) - you will need to click the tab that says "Create an event trigger at runtime". In fact, the example in this document link is exactly for the emoji-reaction-added event, so I think it is relevant to your situation.

That is one key aspect to enable further automation in this case. The second key idea I want to tell you about is a pattern that we've seen emerge that we call the 'configurator workflow' pattern. The idea here is that your app will have two workflows: one to do whatever the thing your app does (do something when someone reacts with an emoji), and another workflow to _configure_ the first. This configuration workflow would use a custom function that creates a trigger dynamically. A typical configuration workflow might look like the following:

1. It is triggered by a [link trigger](https://api.slack.com/automation/triggers/link) - maybe one that is available globally for the entire workspace, or maybe only one that is available in a private channel for administrators.
2. The workflow's first step is to collect information on how to configure a new event trigger for the main app workflow. This can be done using the [OpenForm built-in function](https://api.slack.com/reference/functions/open_form) - a simple way to create a modal to the user and collect information easily (we also have [a tutorial on how to use OpenForm to collect information generally](https://api.slack.com/automation/forms)). Specifically for your case, you would want the form to collect one or more `channel_id`s. By specifying the [types of the form fields](https://api.slack.com/automation/forms#type-parameters), the relevant UI form element will be rendered for you. In the case of a `channel_id`, a channel drop-down menu picker will be rendered.
3. The outputs of this OpenForm function will return the form values - in your case, the channel(s) selected.
4. You can then pass these form outputs to the inputs of a custom function that calls the `workflows.triggers.create` API I mentioned earlier, to dynamically create an event trigger based on the channels selected from the OpenForm step.

I think a good example for you would be the [deno-message-translator sample app](https://github.com/slack-samples/deno-message-translator) we have. This app uses a configurator workflow which actually creates an emoji-reaction-added event trigger dynamically to selected channels - I think your exact use case. Worth noting that this app has an even more advanced configurator workflow than what I described above: it will actually search for previously-created matching event triggers and update them with a new channel list if necessary, will auto-join any such configured channels, and tons of other nice little app improvements.

I hope this helps!

**Comment by tomas-zijdemans-vipps** [comment]
Thanks for the detailed answer @filmaj ! 

I was reviewing how this was done in [the simple survey sample](https://github.com/slack-samples/deno-simple-survey/blob/main/functions/configure_events.ts). It is definitely a path I will explore. As you say, it is quite advanced, so hopefully this could be streamlined somehow in the future.

Maybe we need to have this pattern built in? Offer a new "Configuration Trigger" in the SDK? It could for example have a list of the triggers it's allowed to configure.

> 1. It is triggered by a [link trigger](https://api.slack.com/automation/triggers/link) - maybe one that is available globally for the entire workspace, or maybe only one that is available in a private channel for administrators.

Sorry, I couldn't find in the documentation how to add a Link trigger globally for the entire workspace. Could you point me in the right direction?

**Comment by filmaj** [comment]
> Sorry, I couldn't find in the documentation how to add a Link trigger globally for the entire workspace. Could you point me in the right direction?

Sure! The link trigger is by default global. It is just a link that is shareable anywhere in Slack. You could e.g. pin it or bookmark it to some channel where your workspace users would go to get help or submit requests related to the app, or the workspace, in general.

> Maybe we need to have this pattern built in? Offer a new "Configuration Trigger" in the SDK? It could for example have a list of the triggers it's allowed to configure.

It is a good idea, the implementation details here would be complex, but I understand and reciprocate the sentiment. Since the platform is so new, many of these patterns are _just_ emerging. I will certainly raise this feedback.
