### ISSUE TITLE
Timestamp returned by `SendMessage` function is inaccurate

### ISSUE THREAD

**Issue by skatsuta** [slackapi/deno-slack-sdk#168]
Hi, thank you for developing the New Slack Platform.
It's great to be able to build Slackbots in such a flexible way.

However, I have found an issue with the current behavior of the `SendMessage` function.
It seems that this is not really a problem with the SDK, but with the implementation of the `SendMessage` function on the Platform side.
But I was not sure where to report this issue, so I am reporting it here.
Please let me know if there is a more appropriate place to report it.

On Slack Platform v2.0.0 with the Deno Slack SDK v2.1.0, I have found that the timestamp in the return value of the result of sending a message using the `SendMessage` function is not accurate enough to identify the posted message.

For example, if a message is posted in a workflow as follows, the timestamp in the return value will look like this:

```ts
const sendMessageStep = SomeWorkflow.addStep(
  Schema.slack.functions.SendMessage,
  {
    channel_id: "CXXXXXXXXXX",
    message: "some message",
  },
);
// sendMessageStep.outputs:
// {
//   "message_link": "https://xxx.slack.com/archives/CXXXXXXXXXX/p1681618561535499",
//   "message_timestamp": "1681618561",
//   "message_context": "..."
// }
```

However, if I then try to update the content of this message with this timestamp using the `chat.update` API, passing this `message_timestamp` value as is to the `ts` parameter of the API will result in a `message_not_found` error and the message cannot be updated.

Guessing from the URL of the `message_link` field, it seems that in this case the timestamp should be `1681618561.535499` instead of `1681618561`.

Therefore, to be able to update the posted message later, the `message_timestamp` field should be a decimal timestamp that can be passed directly to the `ts` parameter of the `chat.update` API.
Otherwise, there is no way to update it later except by sending a message directly using the `chat.postMessage` API instead of the `SendMessage` function to get a correct timestamp.

This timestamp inaccuracy issue should be reproducible no matter how `SendMessage` is called.

Note that on Slack Platform v1.21.0 with the Deno Slack SDK v1.6.0, the old `message_ts` field returned by the `SendMessage` function contained an accurate timestamp that could be passed to the `chat.update` API to update the posted message.
Therefore, this issue is considered a regression of sorts in Platform v2.0.0.

Thanks!

**Comment by shapirone** [comment]
Thanks for writing in @skatsuta  We've recently made some updates to the `SendMessage` function and the old `message_ts` output and the new `message_timestamp` aren't compatible. The new `message_timestamp` value is intentionally a Unix timestamp, while we were including additional Slack specific details in the old `message_ts` output. Luckily we still surface the `message_ts` as a property on the `message_context` object that is being shown in your sample output. To access this, you should be able to pass `message_context.message_ts` in the function using the `chat.update` API.

We're currently working on updating our docs to reflect this information 🙇

**Comment by skatsuta** [comment]
Thanks for getting back to me so quickly @shapirone!
Ah I see, it is contained within the `message_context` field!
I confirmed that `message_context.message_ts` can indeed be used to update the message with the `chat.update` API.
Thank you so much for letting me know about that!
