### ISSUE TITLE
 error: function execution exceeded 15.0s timeout

### ISSUE THREAD

**Issue by tomas-zijdemans-vipps** [slackapi/deno-slack-sdk#181]
Question:
I ran into this error yesterday, I assume there is a hard limit that functions need to execute within 15 seconds?

Could this be increased? Or made configurable? This is a function that loads data from Salesforce (using the SF bulk API. It seems SF is quite unpredictable in how long it takes to complete the query).

I could work around the problem by splitting up my function, but that's not ideal - and feels a bit like cheating :D

**Comment by filmaj** [comment]
Hey @tomas-zijdemans-vipps, thanks for writing in.

Indeed, hosted functions have a hard limit of 15 seconds. There are no plans to change this.

I hope that we can address this limitation by providing more asynchronous cloud architectural primitives to users: queues and such. Unfortunately, I cannot provide any timelines or specifics about this at this time.

One admittedly hack-y workaround I've employed thus far is the following:

1. Split up longer-running workloads across different workflows.
2. Have these workloads triggered by a [Scheduled Trigger](https://api.slack.com/automation/triggers/scheduled).
3. Have one workflow invoke another workflow by creating a runtime [scheduled trigger](https://api.slack.com/automation/triggers/scheduled) dynamically from a custom function in one workflow for `time.now() + 2 seconds` (or some such delay) (head to [this documentation](https://api.slack.com/automation/triggers/scheduled) and click the "Create a scheduled trigger at runtime" tab).

I will keep this issue open until we can address it better than the above workaround.

**Comment by tomas-zijdemans-vipps** [comment]
Thanks :) And no worries, I found a solution
