### ISSUE TITLE
How to return a Custom Type

### ISSUE THREAD

**Issue by onmax** [slackapi/deno-slack-sdk#184]
I am currently using the Deno Slack SDK and have defined a custom type as per the [documentation](https://github.com/slackapi/deno-slack-sdk/blob/main/docs/types.md). However, I am having trouble defining an instance of that type and returning it in a custom function.

<details><summary><code>EstablishmentType</code></summary>
<p>

```ts
import { Schema } from "https://deno.land/x/deno_slack_sdk@2.1.4/mod.ts";
import { DefineType } from "https://deno.land/x/deno_slack_sdk@2.1.4/types/mod.ts";

const EstablishmentType = DefineType({
  name: "Establishment",
  type: Schema.types.object,
  description: "Establishment information",
  properties: {
    uuid: { type: Schema.types.string },
    name: { type: Schema.types.string },
    address: { type: Schema.types.string },
    rating: { type: Schema.types.number },
    lat: { type: Schema.types.number },
    lng: { type: Schema.types.number},
    category: { type: Schema.types.string },
    gmaps_types: {
      type: Schema.types.array,
      elements: {
        type: Schema.types.string,
      },
    },
    place_id: { type: Schema.types.string },
    photo: { type: Schema.types.string, default: "" },
    provider: { type: Schema.types.string },
    buy: {
      type: Schema.types.array,
      articles: {
        type: Schema.types.string,
      },
    },
    sell: {
      type: Schema.types.array,
      articles: {
        type: Schema.types.string,
      },
    },
  },
  required: [
    "uuid",
    "name
    "address",
    "rating",
    "lat",
    "lng",
    "category
    "gmaps_types",,
    "place_id
    "provider
    "buy
    "sell
  ],
});

export { EstablishmentType };

```

</p>
</details 

I am trying to create and return an instance of `EstablishmentType` from a Slack function. However, I'm not sure if I'm doing it correctly. 

This is what my code looks like now:

<details><summary>Details</summary>
<p>

````ts
import { DefineFunction, Schema, SlackFunction } from deno-slack-sdk/mod.ts
import { deleteEstablis

**Comment by filmaj** [comment]
Hello! Thanks for writing in. Hopefully we can get to the bottom of the problem.

I think perhaps your "Details" section got cut off as it seems incomplete.

Also, can you post the command you are running and any error output you see from running the `slack` CLI, or however it is you are triggering a problem?
