### ISSUE TITLE
no more than 50 properties allowed (failed_constraint) Source: /functions

### ISSUE THREAD

**Issue by benjrich-jasper** [slackapi/deno-slack-sdk#185]
Receiving the error `no more than 50 properties allowed (failed_constraint)
Source: /functions` when running `slack manifest validate`. 

Am I understanding this right that there is a limit of 50 on custom functions? If so, I'm having a hard time seeing the logic in the decision to allow 100 workflows, but limit us to 50 functions. Are we expected to make most of the workflows using built-in functions? 

![Screenshot 2023-06-21 at 10 51 34 AM](https://github.com/slackapi/deno-slack-sdk/assets/115656113/ee26168a-d670-4cea-812b-92afd066ce9f)

**Comment by filmaj** [comment]
Hey @benjrich-jasper, thanks for asking the question. Indeed, that is indeed the current limit, but we're open to tweaking it. If we bumped it to 100 would that unblock you?

**Comment by benjrich-jasper** [comment]
Yes @filmaj that would definitely unblock us for the time being. But I think we'll run into that limit again before we hit the 100 workflow limit. 

Thanks for being open

**Comment by filmaj** [comment]
No worries, appreciate you filing the issue and letting us know what's getting in your way! Would you mind sharing any more details about your use case that is leading to these limits being pushed? Are all the custom functions different, or more or less the same, maybe with different parameters? Any other patterns emerging that would be useful for us to know as we evolve the platform?

FYI, I am working on a pull request internally to bump the 50 function limit to 250. Will keep this issue open until it is deployed to production.

**Comment by benjrich-jasper** [comment]
Perfect thank you!

We are building an app that can handle interactions w/ nearly all other applications from within slack.
The main limitation we've seen is the inability to have any logic within the workflow itself. If we could get at least simple conditional statements to work in the workflow without needing a custom function, that would help a ton. 

I'm looking through our other functions to find some other patterns and will get back to you.

**Comment by benjrich-jasper** [comment]
Main purpose of our custom functions:
1. Interacting w/ Slack's API (Should be built-in functions)
2. Sending custom blocks and block action handling (could handle in the workflow?)
3. Interacting with 3rd party API (need custom functions)

**Comment by filmaj** [comment]
Hey @benjrich-jasper I believe the bump up to 250 function is now deployed.

Going to close this issue, but feel free to re-open if there's still more to discuss here or you find it is still an issue.
