### ISSUE TITLE
Configuring HTTP method in `identity_config`

### ISSUE THREAD

**Issue by rmhartog** [slackapi/deno-slack-sdk#191]
While developing a new app for the Slack platform, I ran into an issue integrating with an OAuth2 provider. Specifically, this provider requires an HTTP POST on their `/userinfo` endpoint, rather than the standard GET. It is unlikely that they will be changing this any time soon.

It would be nice to allow overriding the method using `identity_config.method` which would default to `GET`, similar to how custom headers are exposed today.

**Comment by filmaj** [comment]
Hey @rmhartog thanks for filing the issue!

I have raised this with the relevant OAuth2 provider team internally; as I hear back on their plans about this I will keep this thread updated.

**Comment by filmaj** [comment]
FYI this is on the team's internal roadmap but no specific timeline is planned to deliver on this at the moment.

**Comment by filmaj** [comment]
Hello! We added support for this in #217. The documentation for this, it looks like, is still missing from https://api.slack.com/automation/external-auth#properties so I will follow up on that. However, you should be able to set this via `identity_config.http_method_type = "POST"` in your code. Full details for the properties supported on `identity_config` should be available via autocomplete in any modern editor, or you can also look at [this section of the PR that added support for this feature](https://github.com/slackapi/deno-slack-sdk/pull/217/files#diff-cb0839a926cfaea6a79a6126e3ab6526905f24d66c6c8d677c3e1aa5b76f2e1fR7-R24).
