### ISSUE TITLE
Question : Slack Apps Event Triggers not invoking the ThirdParty externalAuthProvider OAuth when invoking the Workflow

### ISSUE THREAD

**Issue by pranith12345** [slackapi/deno-slack-sdk#193]
Hi I am currently working on creating a new Generation Slack App which uses a Third Party OAuth for the Workflow .
I added the below in the function definition which will trigger the OAuth Workflow .

```
 accessTokenId: {
    credential_source: "END_USER"
  },
```

 I created an Event Trigger and a Link Trigger . The link Trigger is invoking the OAuth Workflow when the command is triggered . But when the Event trigger is generated , the OAuth workflow is not getting triggered.

 Will the Oauth Workflow be trigggered when the event is raised for slack app.

**Comment by filmaj** [comment]
Hey @pranith12345 !

At this time, only link triggers are supported for end-user auth, as this is the only trigger guaranteed to stem directly from an end-user interaction (not all event triggers come from an end-user).

Going to close this issue down, but if you have further questions, feel free to re-open or file another issue.

**Comment by r-dev-limited** [comment]
I dont get it though, so lets say you have app_mention event, and user mentions app, we cant use that user interaction to call external service using oauth ?

https://api.slack.com/automation/external-auth#workflow

How exactly to choose that persona in such moment ? I mean I dont want to ask users all the time to invoke shortcuts / paste links just to perform action, which should be an event
