### ISSUE TITLE
Question: How to add Slash Commands in a Slack CLI app

### ISSUE THREAD

**Issue by despolov** [slackapi/deno-slack-sdk#206]
Hello,

Im currently developing an app using the slack cli way and I want to add /slash commands support. How can this be achieved using the CLI way?

**Comment by filmaj** [comment]
Hello!

There is no support for slash commands in the new automation platform. If you create a workflow and pair a shortcut trigger to it, it will become searchable in the Slack client in the same way that slash commands are, though. So while the entry points are subtly different (between slash commands and shortcut triggers), they are essentially the same thing. Hopefully the two are interchangeable for you. If not, let me know and let's discuss!

**Comment by despolov** [comment]
Got it, thanks. I guess shrotcut triggers will do the work for me. 
The only bad part I could name now is that, there will be no way to pass data to the shortcut trigger from the message composer

**Comment by filmaj** [comment]
@despolov that is a good point, however, you could just as, if not more! easily collect data from the user using the [OpenForm step](https://api.slack.com/reference/functions/open_form) as the first step in your workflow. This gives users a rich UI that offers many niceties (such as selecting dates or users or channels, etc.) for providing data to your workflows.

Going to close this issue but feel free to re-open if you'd like to discuss more.

**Comment by AndrewHUNGNguyen** [comment]
Will there be future support for the slash command?
