### ISSUE TITLE
Question: How to remove the "Review workflow access" window when clicking a button in a Slack CLI app

### ISSUE THREAD

**Issue by despolov** [slackapi/deno-slack-sdk#219]
Hi, 

I am currently developing a next-generation platform app using Slack CLI. I have deployed the app in my workspace and currently everytime someone from my team click an action button or triggers a shortcut trigger, this window shows up. 
![image](https://github.com/slackapi/deno-slack-sdk/assets/50716452/f4117c80-7079-44b5-9ca9-d818242a18c3)
How can this be avoided?

**Comment by pranith12345** [comment]
I don't think this window can be avoided . This Window will be shown when a workflow execution is started .

**Comment by filmaj** [comment]
Hello! Sorry for the late response but I did some digging to find out where this dialog comes from.

Essentially, this is a visual "speedbump" for workflows that rely on what we at Slack call "risky scopes." The idea is that we are double-checking and making very sure an end-user is aware of what kinds of permissions they are granting to a workflow when they use relatively-privacy-sensitive scopes. The list of these scopes we consider privacy-sensitive are:

- `groups:history`
- `mpim:history`
- `im:history`
- the various `groups:write.*` scopes

I think in the screenshot you originally posted, @despolov, it is for the `im:history` scope (essentially: private message contents).

There is no way to get around this modal (we show it to err on the side of protecting user data), but, hopefully just being aware of this can help you develop and plan your applications and workflows appropriately.

Going to close this issue but if you have more questions or concerns feel free to re-open.

**Comment by maxmiranda** [comment]
@filmaj Please help me understand why based on my Manifest, we're seeing the Review Workflow prompt

<img width="515" alt="Image" src="https://github.com/user-attachments/assets/fd590b1c-63b5-49d3-921f-9480ffaf45a3" />
```

/**
 * The app manifest contains the app's configuration. This
 * file defines attributes like app name and description.
 * https://api.slack.com/automation/manifest
 */
export default Manifest({
  name: "Update Jira Functions",
  description: "Update Jira tickets from Slack",
  icon: "assets/prioritization.png",
  functions: [PriorityMappingFunction, CreateJiraIssue],
  workflows: [CreateJiraIssueWorkflow],
  outgoingDomains: ["jira-domain"],
  botScopes: [
    "workflow.steps:execute",
  ],
});

```

**Comment by gpdb01** [comment]
I recently ran into this issue as well with a template called "Ask an Expert". Some of these 'risky scopes' will pop review access dialog in private channels while they won't pop in public channels.
