### ISSUE TITLE
[Question] How to send acknowledgment on response

### ISSUE THREAD

**Issue by nielniel** [slackapi/deno-slack-sdk#223]
**Question**

I'm currently working on implementing a modal that allows users to fetch information from an API. However, the backend processing takes more than 3 seconds, and I'm encountering the error message, "We had some trouble connecting. Try again."

I've tried searching online for examples, but I couldn't find any workaround on this. I would greatly appreciate assistance with this matter.

**Environment**

- Deno version: 1.36
- TypeScript version: 5.1.6
- macOS version: 13.5.2

**Comment by filmaj** [comment]
Currently there is no way to do so. If your custom functions creates interactive experiences like modals, then the relevant interactivity handlers must finish their processing within 3 seconds.

**Comment by filmaj** [comment]
Going to close this as duplicates of #179 and #227.

I think in the future we will work on providing more functional primitives to developers, to more easily handle these situations.
