### ISSUE TITLE
[BUG] icon is not changed by manifest

### ISSUE THREAD

**Issue by spoike** [slackapi/deno-slack-sdk#242]
**The `deno-slack` versions**

    "deno-slack-sdk/": "https://deno.land/x/deno_slack_sdk@2.4.1/",
    "deno-slack-api/": "https://deno.land/x/deno_slack_api@2.1.2/",

**Deno runtime version**

deno 1.37.2 (release, x86_64-apple-darwin)
v8 11.8.172.13
typescript 5.2.2

**OS info**

ProductName:            macOS
ProductVersion:         14.0
BuildVersion:           23A344
Darwin Kernel Version 23.0.0: Fri Sep 15 14:42:42 PDT 2023; root:xnu-10002.1.13~1/RELEASE_X86_64

**Describe the bug**

The bot icon doesn't change when updating the manifest and new image to the assets folder. There are no warnings about any failed upload or anything when running or reinstalling the app.

**Steps to reproduce**

On an already installed app:

1. Put a png image to the assets folder (named `service_bunny.png`)
   ![service_bunny.png](https://github.com/slackapi/deno-slack-sdk/assets/9253/346ccafc-8ff6-4c77-92ad-4f35c450358e)
2. Update `icon` in manifest.ts to point to the new image
3. `slack run`

**Expected result**

The new app icon should be displayed for the app/bot instead of the default one.

**Actual result**

From the about tab:
<img width="618" alt="image" src="https://github.com/slackapi/deno-slack-sdk/assets/9253/f422ce43-110a-43d3-809a-0325ec95c429">

From the messages tab (and also the user icon):
<img width="654" alt="image" src="https://github.com/slackapi/deno-slack-sdk/assets/9253/ef223afe-bdaf-435f-93cc-fe17a4b7babf">

**Requirements**

Please read the [Contributing guidelines](https://github.com/slackapi/deno-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by WilliamBergamin** [comment]
Hello @spoike thanks for writing in 💯 

I was able to reproduce this bug, it does seem like `slack run` does not update the app icon, but using `slack deploy` worked

This is potentially a backend limitation, I'm trying to figure out if this was intentional or not

**Comment by tomas-zijdemans-vipps** [comment]
This has always been the behaviour in the SDK. Only deploy will set the icon. 
I first thought it was a bug, but then started thinking it might be because several developers can be running a dev version at the same time (so, you have multiple versions of the same app running simultaneously). The only way to differentiate them, in the Slack UI, is by looking at the different icon colours. It also makes it easier to spot the deployed version of the app when adding it to channels, etc.

**Comment by filmaj** [comment]
Yes just wanted to chime in that this is expected behaviour, exactly for the reason Tomas stated. `slack deploy` will update the icon, `slack run` will use a stock image that is meant to represent "this is a locally running, and thus unstable / in development, app."

**Comment by spoike** [comment]
Is this caveat documented anywhere? Because having some attributes in the [Manifest](https://github.com/slackapi/deno-slack-sdk/blob/main/docs/manifest.md) not be updated while running `slack run` is confusing behavior for developers.

At least it has been a time waster for me debugging it until I reported it here.

**Comment by filmaj** [comment]
Totally fair @spoike ! I will follow up with our documentation team to make sure we document this.
