### ISSUE TITLE
[QUESTION] Changing / setting the workflow permissions via CLI

### ISSUE THREAD

**Issue by mcsescott** [slackapi/deno-slack-sdk#260]
In a next-gen app, when creating a link trigger (for a workflow), is there a way to specify permissions of "who can run and find this workflow" ?

I was looking at the [documentation here](https://api.slack.com/automation/triggers/link), and couldn't find a way.  My current workaround would be to go into the admin console  **_(https://app.slack.com/manage/TEAMID/integrations/profile/APPID/steps)_** and change it, but would like to be able to do this programmatically when creating the trigger.

**Comment by filmaj** [comment]
Hey sorry for the late response! Holidays and all that. Back in action, though!

There is a document called [Trigger Management, and specifically Manage access to a trigger within](https://api.slack.com/automation/triggers/manage#manage), that is probably what you are looking for.

The key is that gating permissions is not done at the workflow level, but rather at the trigger level: you can control who has access to a trigger that invokes your workflow. You can also create different triggers with different access levels.
