### ISSUE TITLE
[QUERY] The hint about form

### ISSUE THREAD

**Issue by AceRui** [slackapi/deno-slack-sdk#263]
```
const inputForm = MondayWorkflow.addStep(
  Schema.slack.functions.OpenForm,
  {
    title: 'Automation Request',
    interactivity: MondayWorkflow.inputs.interactivity,
    submit_label: 'Submit',
    fields: {
      elements: [
        // title
        {
          name: 'item',
          title: 'Item',
          type: Schema.types.string,
          hint: "需求内容"
        },
```
Thie is a part of my codes,is there something wrong with it, why is there no parameter hint when my form opens?
![截屏2024-01-04 12 48 36](https://github.com/slackapi/deno-slack-sdk/assets/147489583/287df662-ca78-4bf7-8b5d-2242ffa4aa73)

**Comment by filmaj** [comment]
Hello, there is no `hint` available on OpenForm fields.

Please see the OpenForm element type parameters, and the available fields based on each `type` for each form element [in our documentation on the topic](https://api.slack.com/reference/functions/open_form#type-parameters).
