### ISSUE TITLE
We are integrating slack with Amazon Q but not getting any response in slack

### ISSUE THREAD

**Issue by SakthiPriyanka** [slackapi/deno-slack-sdk#265]
We are integrating slack with Amazon Q using this https://github.com/aws-samples/amazon-q-slack-gateway/blob/main/README.md. But not getting any response in slack bot. Let me know if I am missing anything in slack side. 

Please refer the manifest file https://github.com/aws-samples/amazon-q-slack-gateway/blob/main/slack-manifest-template.json. This is the setting we followed to create the slack bot.

**Comment by filmaj** [comment]
It's unclear how you set this up and how this relates to the deno-slack-sdk project.

Where is this app deployed?

**Comment by filmaj** [comment]
Haven't heard back, closing.

**Comment by leeleavitt** [comment]
You need to be Pro to use Q business slack integration.
