### ISSUE TITLE
[FEATURE] Supports OAuth2 provider which does not supply identity endpoint

### ISSUE THREAD

**Issue by koyama-tagbangers** [slackapi/deno-slack-sdk#306]
**Description of the problem being solved**

Thanks to the Slack platform for its great OAuth2 integration.

However, there is an issue where some OAuth2 providers do not provide an endpoint to retrieve an authenticated user.

One example is [Tempo.io](https://www.tempo.io/), which can get access tokens but cannot get authenticated user.
https://community.developer.atlassian.com/t/oauth2-provider-action-retrieveprofile-with-tempo-oauth/55371

I'd like to have the option to only keep one token per end user without retrieving the authenticated user.

**Alternative solutions**

For the OAuth flow to succeed, specify dummy API that returns fixed JSON value in the options `OAuth2ProviderOptions#identity_config`.

```ts
const TempoProvider = DefineOAuth2Provider({
  provider_key: "tempo",
  provider_type: Schema.providers.oauth2.CUSTOM,
  options: {
    provider_name: "Tempo",
    ...
    identity_config: {
      // Always returns {"value": "dummy"}
      url: "https://my-mock-server.app",
      // Always "dummy" value
      account_identifier: "$.value",
    },
  },
});
```

According to the Slack Platform documentation, obtained authenticated user via `identity_config` configuration is used for user selecting.

https://api.slack.com/automation/external-auth#identity-properties
> If the same user has two different accounts for the the same provider, but the identity_config is configured such that the same external_user_id value (obtained via the identity_config property) is returned in case of both the accounts, the user will not be able to issue multiple tokens for multiple accounts as existing tokens will be overwritten if the external user IDs are the same. This identity is what is used to identify different accounts for a user for the same provider, and only one token per identity is stored for a user, team, and provider combination.

My understanding of this is that even if value of `identity_config.account_identifier` is a fixed, a separate token is stored for each end user that executes the workflow.

**Comment by WilliamBergamin** [comment]
I've been querying internally on this subject, I don't have an update yet, but it does seem like [Tempo.io](https://www.tempo.io/) is the first use case for this

It does seem like [Tempo.io](https://www.tempo.io/) could benefit from exposing a `myself API` type of endpoint, I would recommend reaching out to them as well in order to expose an endpoint of this nature

**Comment by WilliamBergamin** [comment]
Hi @koyama-tagbangers I have an update on this

I appear that you would be able to provide a "dummy" endpoint for the `identity_config`, ideally the value returned by the "dummy" endpoint should be unique for each user

The major drawback of this approach is that a user can only have one [Tempo.io](https://www.tempo.io/) token saved per slack account , for example Slack would not be able to distinguish the tokens minted for a slack user that wishes to use a [Tempo.io](https://www.tempo.io/) company account and a personal account.

**Comment by WilliamBergamin** [comment]
> set dummy REST API URL which returns {"id": "<random-uuid>"} to identity_config.url?

Yes this should work, but I have not tested it out yet

> What are the effect of the returned value is fixed?

Slack users will only be able to be logged in to 1 Tempo.io account at a time, for example during your development process Slack will not be able to store a Dev token and a Prod token simultaneously on behalf of your Slack Account

> Could you provide a way to set a fixed value on the client without fetching to the dummy endpoint?

We are in the process of potentially adding a way to opt out of `identity_config` at the cost of only being able to store one token per slack account, I do not have an ETA on this feature
