### ISSUE TITLE
[QUERY] Create Channel canvas using Slack API's ( "@slack/bolt",  "@slack/web-api")

### ISSUE THREAD

**Issue by harshbhardwaj29** [slackapi/deno-slack-sdk#307]
**Question**

Is it supported to create canvas in channel using slack access token via slack bot or slack web API

**Context**

I have slack access token of a user, using that i want to create canvas in channels on behalf of that user.

**Environment**

**Requirements**

Please read the [Contributing guidelines](https://github.com/slackapi/deno-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by harshbhardwaj29** [comment]
@filmaj As canvas functions are part of deno-slack-sdk, i would like to know, if it possible to create using slack bolt or web-api  Sdks

**Comment by filmaj** [comment]
Canvas APIs are not exposed via HTTP at this time, like our other [methods](https://api.slack.com/methods) are. The only way to access these APIs at this time is by using the workflow automations Slack built-in functions by building it either using the deno-slack-sdk or by building a workflow in Workflow Builder directly.

If this is a feature that you would like access to, I recommend emailing feedback@slack.com and mentioning you are emailing to ask for Canvas HTTP APIs. This would surface your request to the decision makers at Slack who can impact this most directly.
