### ISSUE TITLE
[QUERY] Creating 'user select' field in workflow form 

### ISSUE THREAD

**Issue by mirianbatista** [slackapi/deno-slack-sdk#310]
**Question**

Hello, I am trying to create a user select field in a workflow form, but I am having difficulties. I tried to make it similar to this one ([ref](https://github.com/slackapi/deno-slack-sdk/blob/main/src/schema/slack/functions/create_channel.ts#L21)): 
```ts
manager_ids: {
  type: SchemaTypes.array,
  description: "Search all people",
  title: "Select Channel Manager(s)",
  items: { type: SlackTypes.user_id },
},
```

But it didn't work out. I tried to make it similar to this one as well ([ref](https://github.com/slackapi/node-tasks-app/blob/main/user-interface/modals/new-task.js#L23C1-L27C9), [ref](https://youtu.be/wp-0ntNmpW0?t=182)), but once again, no success:
```js
Blocks.Input({ label: 'Assign user', blockId: 'taskAssignUser' }).element(
  Elements.UserSelect({
    actionId: 'taskAssignUser',
  }).initialUser(currentUser),
),
```

I also tried searching for examples/references by looking up `user_select`/`userSelect`/`user select` in this repository and in deno-slack-api, but I really can't figure it out, can someone help me with an example?

**Context**

What I am trying to do is this field that shows the users from slack:
![image](https://github.com/slackapi/deno-slack-sdk/assets/17030383/cb132004-8949-4a87-a596-ac2da13fa905)
I am following the [readme](https://github.com/slackapi/deno-slack-sdk?tab=readme-ov-file#create-a-function) to create the function, workflow and trigger, and for the simpler fields the documentation works perfectly, but for this type of field, I couldn't find anything.

**Environment**

 

```
    "deno-slack-sdk/": "https://deno.land/x/deno_slack_sdk@2.9.0/",
    "deno-slack-api/": "https://deno.land/x/deno_slack_api@2.3.2/"

    deno 1.42.3 (release, x86_64-unknown-linux-gnu)
    v8 12.3.219.9
    typescript 5.4.3
    
    #29~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC
```

**Requirements**

Please read the [Contributing guidelines](https://github.com/slackapi/deno-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by WilliamBergamin** [comment]
Hi @mirianbatista thanks for writing in 💯 

Have you taken a look at our [deno-issue-submission](https://github.com/slack-samples/deno-issue-submission) sample project, in the there is a good example of using the [open form slack function ](https://github.com/slack-samples/deno-issue-submission/blob/main/workflows/submit_issue.ts#L31)

The following should open a form with a user dropdown

```ts
const inputForm = SubmitIssueWorkflow.addStep(
  Schema.slack.functions.OpenForm,
  {
    title: "Submit a user",
    interactivity: SubmitIssueWorkflow.inputs.interactivity,
    submit_label: "Submit",
    fields: {
      elements: [{
        name: "user_id",
        title: "Select a user",
        type: Schema.slack.types.user_id,
      }],
      required: ["user_id"],
    },
  },
);
```

Let me know if this helps

**Comment by mirianbatista** [comment]
amazing!!!!! @WilliamBergamin, thank you so much for sharing this example, it was exactly what I needed!!
