### ISSUE TITLE
[QUERY] Custom Workflow Steps - Checkboxes

### ISSUE THREAD

**Issue by mcsescott** [slackapi/deno-slack-sdk#339]
I'm building a custom workflow step (done many of them), and now trying to add some checkboxes to the modal/form/configuration step.

According to the [documentation](https://api.slack.com/automation/types#array) when specifying an array, I can have a `display_type` of checkboxes, however I can't get it to work.  No errors when doing a slack run, it just doesn't show it as checkboxes.  It still shows it as a dropdown.  I'm not trying anything fancy, just using the sample array definition from the example provided.

```
export const datefunctions_FunctionDef = DefineFunction({
  callback_id: "date_functions_function",
  source_file: "functions/date_functions.ts",
  title: "Date Functions",
  description: "Hi filmaj",

  input_parameters: {
    properties: {
      "departments": {
        "title": "Your department",
        "type": "array",
        "items": {
          "type": "string",
          "enum": [
            "marketing",
            "design",
            "sales",
            "engineering",
          ],
        },
      },
      "departments_with_checkboxes": {
        "title": "Your department (this should be checkboxes)",
        "type": "array",
        "items": {
          "type": "string",
          "enum": [
            "marketing",
            "design",
            "sales",
            "engineering",
          ],
        },
        minItems: 2,
        display_type: "checkboxes",
      },
    },
    required: [],
  },
//...
```

![image](https://github.com/user-attachments/assets/ae6a50a2-672a-4796-9c2f-308f15963bbc)

I've even tried the following, and this doesn't work either:

```
      inputstring: {
        type: Schema.types.array,
        title: "Your input expression", //The variable used for subsequent steps
        items: {
          type: Schema.types.string,
          enum: ["marketing", "design", "sales", "engineering"],
        },
        display_type: "checkboxes",
      },
```

So... How to add checkboxes in a custom workflow configuration step, or am I reading the documentation wrong and it isn't supported?

**Comment by filmaj** [comment]
Hey @mcsescott 👋 
I am still investigating this, but I _believe_ this parameter should not be documented for coded workflow builders. I am still getting confirmation but I believe this parameter is only used by the Workflow Builder UI. It doesn't make sense to me that a custom function in a coded workflow context has any concept of 'appearance', as coded workflow custom steps are UI-less.

**Comment by filmaj** [comment]
I have confirmed that custom functions should _not_ be setting `display_type` on their input parameters. It's a bit of convoluted problem, but essentially `display_type` should be used in [`OpenForm` steps](https://api.slack.com/automation/forms). You can create a form to collect input via `OpenForm`, and you can specify different input fields this way. You can specify an Array-type input, and it is with certain _kinds_ of array OpenForm input elements that you can specify `display_type`. For example, with this workflow step:

```javascript
SampleWorkflow.addStep(Schema.slack.functions.OpenForm, {
    title: "Give someone kudos",
    interactivity: SampleWorkflow.inputs.interactivity,
    description: "Continue the positive energy through your written word",
    fields: {
      elements: [{
        name: "doer_of_good_deeds",
        title: "Whose deeds are deemed worthy of a kudo?",
        description: "Recognizing such deeds is dazzlingly desirable of you!",
        type: Schema.types.array,
        items: {
          type: Schema.types.string,
          enum: ["one", "two", "three"],
        },
        display_type: "checkboxes",
      }],
      required: ["doer_of_good_deeds"],
    },
  }
);
```

... you would get this kind of form rendering:

<img width="520" alt="Screenshot 2024-07-18 at 2 39 36 PM" src="https://github.com/user-attachments/assets/8a150ae4-781d-4c77-9ddf-7e11313ab4a7">

I'm still following up to figure out what other _kinds_ of array types can be used w/ `display_type`. I tried with, for example, an array of plain string, but would get an `invalid_form_inputs` error at runtime. This makes sense: an array of generic strings can't be explicitly enumerated into checkboxes, but an array of string _enums_ can. So this tells me this `display_type` property on OpenForm can't apply to any type.

**Comment by filmaj** [comment]
OK, did more digging through this code, I am 99% certain `display_type` _only_ applies to:

- OpenForm array-type fields,
- The OpenForm array input field must be a string, and it must also specify `enum`

... just like the example I posted in my last message.

Docs are being updated as I type this!

Apologies for the confusion and the wait 🙇

**Comment by mcsescott** [comment]
Thanks for checking and the follow-up.   I'm all about workflows and custom steps, so just wish they had a bit more flexibility on things that we can do with regular modals.

**Comment by lukegalbraithrussell** [comment]
Hey @mcsescott, [docs are officially updated](https://api.slack.com/automation/forms#type-parameters). I'm going to close this issue, but feel free to reopen or open a new issue if needed!

**Comment by mcsescott** [comment]
Thanks; I see the updated documentation, Please realize this is for a custom step with Workflow builder, not for an OpenForm step.

Consequently, this has always been an issue with Slack's documentation - the options for custom steps in Workflow Builder (both legacy and NextGen) have always been poorly documented, as some things just don't work.
