### ISSUE TITLE
[BUG] Buttons not responding on mobile

### ISSUE THREAD

**Issue by hi-se** [slackapi/deno-slack-sdk#341]
**The `deno-slack` versions**

"deno-slack-sdk/": "https://deno.land/x/deno_slack_sdk@2.9.0/"
"deno-slack-api/": "https://deno.land/x/deno_slack_api@2.3.2/"

**Deno runtime version**

deno 1.43.1 (release, aarch64-apple-darwin)
v8 12.4.254.12
typescript 5.4.3

**OS info**

ProductName:		macOS
ProductVersion:		14.5
BuildVersion:		23F79
Darwin Kernel Version 23.5.0: Wed May  1 20:12:58 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6000

**Describe the bug**

I've been developing a custom Slack App using the Slack Deno framework, which incorporates 'approve' and 'deny' buttons. Previously, these buttons worked on mobile devices, but recently they have stopped responding when pressed, with no requests being logged.

**Steps to reproduce**

1. Open the custom Slack App on a mobile device.
2. Try to press the 'approve' or 'deny' button.
3. Observe that there is no response and no logs are generated.

**Expected result**

The 'approve' and 'deny' buttons should work on mobile devices as they do on desktop environments.

**Actual result**

The buttons do not respond on mobile devices, and no logs are recorded when the buttons are pressed.

**Requirements**

Please read the [Contributing guidelines](https://github.com/slackapi/deno-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by WilliamBergamin** [comment]
Thanks for reporting this 💯 

I was able to reproduce this behavior with the following steps

1. Create a request time off slack app `slack create test-mobile -t https://github.com/slack-samples/deno-request-time-off`
2. `cd test-mobile`
3. Start the app with `slack run`, when prompted to create a trigger, create it.
4. Post the link trigger in a channel, and start the workflow
5. Select the "manager" as yourself and submit a time off request
6. Using a mobile device try clicking `approve` or `deny` button
7. Nothing happens 🔴 
8. Clicking `approve` or `deny` button in the Slack UI works as expected

This seems to be a backend or mobile issue, I will this internally, you can also report this bug using the `/feedback` command in slack or support@slack.com

**Comment by hi-se** [comment]
@WilliamBergamin 
Thank you for the response!

When I first contacted support about the custom application issue, I was advised to open a GitHub issue. However, I'm going to repost my question in light of this.

**Comment by hi-se** [comment]
The mobile app has been updated and the issue has been resolved. I can confirm that the buttons are now responding correctly on mobile. I am therefore closing this issue. Thanks to all involved for their support.
