### ISSUE TITLE
[QUERY] Workflow error handling

### ISSUE THREAD

**Issue by ynkze** [slackapi/deno-slack-sdk#359]
**Question**

Given the Slack datastore example on how to retrieve items:
```
const getResponse = client.apps.datastore.get<typeof DraftsDatastore.definition>({...});
const announcementId = getResponse.item.id; // this is the primary key

if (getResponse.item.icon) {
  const announcementIcon = getResponse.item.icon;
  return {
    outputs: {
      id: announcementId,
      icon: announcementIcon }
  }
} else {
  return {
    error: "Announcement doesn't have an icon assigned"
  }
}
```

on error to get item from datastore will be logged to console and stop the workflow. However, I do not want to stop the workflow because for example: 
1. I am adding a new item to datastore
2. I check if item exist in datastore
3. If item don't exist, I can proceed with adding the item.

The issue is it seems that as long as an error occur the workflow will stop, just wondering if this is intended because it seems using a `try-catch` still causes the workflow to stop.

**Comment by srajiang** [comment]
Hey @ynkze! I'm not sure I fully understand. Are you meaning that if you wrap

```
const getResponse = client.apps.datastore.get<typeof DraftsDatastore.definition>({...});
```
In a try catch, you're saying that the workflow stops running?

You typically need to return a completeSuccess response from your function step in order for the remaining workflow steps to proceed to execute.

**Comment by ynkze** [comment]
> Hey @ynkze! I'm not sure I fully understand. Are you meaning that if you wrap
> 
> ```
> const getResponse = client.apps.datastore.get<typeof DraftsDatastore.definition>({...});
> ```
> 
> In a try catch, you're saying that the workflow stops running?
> 
> You typically need to return a completeSuccess response from your function step in order for the remaining workflow steps to proceed to execute.

Yes, given the context where I checked if item exist in datastore before adding a new item, I want the `getResponse` to fail in this scenario. Is this possible to implement without the workflow halting?

**Comment by filmaj** [comment]
```typescript
const getResponse = client.apps.datastore.get<typeof DraftsDatastore.definition>({...});
```

I think this is missing an `await` in front of it.

**Comment by ynkze** [comment]
> ```typescript
> 
> const getResponse = client.apps.datastore.get<typeof DraftsDatastore.definition>({...});
> 
> ```
> 
> 
> 
> I think this is missing an `await` in front of it.

Yup I think I grabbed it from the example in the documentation, in my code I did use 'await' but overall the same issue with workflow halting applies.

**Comment by filmaj** [comment]
Hi @ynkze, so using the deno-starter-template example app, I was able to build on it to, I think, recreate what you are trying to accomplish in your app. However, the workflow had no 'halting' issues and raising errors were properly raised in the Slack client.

I took the code you see in [the starter template's sample function here](https://github.com/slack-samples/deno-starter-template/blob/main/functions/sample_function.ts) and changed the top of the function like so:

```typescript
    const uuid = inputs.message;

    const getRes = await client.apps.datastore.get<typeof SampleObjectDatastore.definition >({
      datastore: "SampleObjects",
      id: uuid,
    });

    if (getRes.item.object_id) {
      return {
        error: 'message already exists!'
      }
    }
    // inputs.user is set from the interactivity_context defined in sample_trigger.ts
    // https://api.slack.com/automation/forms#add-interactivity
    const updatedMsg = `:wave: ` + `<@${inputs.user}>` +
      ` submitted the following message: \n\n>${inputs.message}`;

    const sampleObject = {
      original_msg: inputs.message,
      updated_msg: updatedMsg,
      object_id: uuid,
    };

    // Save the sample object to the datastore
    // https://api.slack.com/automation/datastores
    const putResponse = await client.apps.datastore.put<
      typeof SampleObjectDatastore.definition
    >({
      datastore: "SampleObjects",
      item: sampleObject,
    });
```

Running the workflow, if the user enters a new message with no previously-stored object, it completes as expected and posts a message. If the user enters a message that was entered previously (and thus was stored in the datastore), it errors as expected. Once the error is raised, the workflow does not continue to execute. This is expected behaviour.

What are you trying to accomplish? It seems you want to handle the error case and continue execution - can you not do that in your custom function code?

**Comment by ynkze** [comment]
> Hi @ynkze, so using the deno-starter-template example app, I was able to build on it to, I think, recreate what you are trying to accomplish in your app. However, the workflow had no 'halting' issues and raising errors were properly raised in the Slack client.
> 
> I took the code you see in [the starter template's sample function here](https://github.com/slack-samples/deno-starter-template/blob/main/functions/sample_function.ts) and changed the top of the function like so:
> 
> ```ts
>     const uuid = inputs.message;
> 
>     const getRes = await client.apps.datastore.get<typeof SampleObjectDatastore.definition >({
>       datastore: "SampleObjects",
>       id: uuid,
>     });
> 
>     if (getRes.item.object_id) {
>       return {
>         error: 'message already exists!'
>       }
>     }
>     // inputs.user is set from the interactivity_context defined in sample_trigger.ts
>     // https://api.slack.com/automation/forms#add-interactivity
>     const updatedMsg = `:wave: ` + `<@${inputs.user}>` +
>       ` submitted the following message: \n\n>${inputs.message}`;
> 
>     const sampleObject = {
>       original_msg: inputs.message,
>       updated_msg: updatedMsg,
>       object_id: uuid,
>     };
> 
>     // Save the sample object to the datastore
>     // https://api.slack.com/automation/datastores
>     const putResponse = await client.apps.datastore.put<
>       typeof SampleObjectDatastore.definition
>     >({
>       datastore: "SampleObjects",
>       item: sampleObject,
>     });
> ```
> 
> Running the workflow, if the user enters a new message with no previously-stored object, it completes as expected and posts a message. If the user enters a message that was entered previously (and thus was stored in the datastore), it errors as expected. Once the error is raised, the workflow does not continue to execute. This is expected behaviour.
> 
> What are you trying to accomplish? It seems you want to handle the error case and continue execution - can you not do that in your custom function code?

Hi @filmaj, yes that is exactly right I want to handle the error and continue execution. The reason is I want user using the workflow to be able to get an error message sent to the slack channel, however right now on error when the workflow stops and user does not get any feedback. I have not been able to found a way to make the workflow continue to send the user an error message using `try-catch` in the custom function, do let me know if that is possible.

**Comment by filmaj** [comment]
@ynkze is it not possible to do whatever you need to do within the conditional that checks for the datastore object existence? Something like:

```typescript
if (getRes.item.object_id) {
  // do not return { error } here, instead send a message to the user, do other things?
}
```

**Comment by ynkze** [comment]
> @ynkze is it not possible to do whatever you need to do within the conditional that checks for the datastore object existence? Something like:
> 
> ```ts
> if (getRes.item.object_id) {
>   // do not return { error } here, instead send a message to the user, do other things?
> }
> ```

Can you give me an example of how to send a message to user from this function here? The only way I know is to pass a message to the function outputs then send to the workflow `SendMessage` function, which does not work because once the `get` fails in this function the workflow will halt.

**Comment by filmaj** [comment]
There is a Slack HTTP API client available as an [argument to your custom function](https://api.slack.com/automation/functions/custom#context) (`client`) which you can use to make any Slack HTTP API calls.

[This sample, for example](https://github.com/slack-samples/deno-timesheet-approval/blob/2c8cb81cffb70102b1d7d70a535955eaa0e71a27/functions/save_hours.ts#L74), calls [the `users.profile.get` HTTP method](https://api.slack.com/methods/users.profile.get). To post a message, you could do this with [the `chat.postMessage` HTTP API](https://api.slack.com/methods/chat.postMessage) instead

**Comment by ynkze** [comment]
Ok thanks its working as intended now, I think I made 2 mistakes:
1. When getting the item since `getResponse.items` returned an array I needed to do `getResponse.items.length === 0` and check if query gives back any item
2. I was returning error which causes the stop in workflow.

**Comment by filmaj** [comment]
Great! I will close this issue down then.
