### ISSUE TITLE
Passing view id of an open modal between Deno functions causing parameter validation failure

### ISSUE THREAD

**Issue by djmgit** [slackapi/deno-slack-sdk#364]
**Question**

I am working on a flow, which comprises of two functions, first function makes an api call to our service and gets back a bunch of data (json).
The second function gets that data, opens a modal, gets input from user and so on.
Now the problem is sometimes the data fetching process is taking longer than 3s as a result the interactivity pointer is expiring and the second function fails.
As an alternative, what I am trying to do is, let the first function open a modal, I am trying to pass the view id of this modal to the second function via first function's output params. But I am repeatedly getting parameter validation failed. Does it mean I cant open a modal in one function and pass its view id to second function? If I pass a junk string using the same parameter it works fine but the moment I keep a modal open via first function, I get parameter validation error.

**Environment**

deno-slack-sdk/": "https://deno.land/x/deno_slack_sdk@2.14.2/",
"deno-slack-api/": "https://deno.land/x/deno_slack_api@2.8.0/",

deno 1.44.4 (release, aarch64-apple-darwin)
v8 12.6.228.9
typescript 5.4.5

ProductName:		macOS
ProductVersion:		13.6.7
BuildVersion:		22G720
Darwin Kernel Version 22.6.0: Mon Apr 22 20:51:27 PDT 2024; root:xnu-8796.141.3.705.2~1/RELEASE_ARM64_T6020

**Comment by djmgit** [comment]
cc: @filmaj

**Comment by filmaj** [comment]
Can you post an overview of your workflow? Particularly important is understanding where the interactivity pointer comes from and how it flows through your entire workflow. Interactivity pointers are a kind of 'key' or password - they are sensitive, they are time-limited, and they _must_ stem from an end-user interaction in the Slack client. Depending on how it is used and the time elapsed between an interactivity pointer getting created by the system and when it is attempted to be used, this may be expected behaviour.

**Comment by djmgit** [comment]
@filmaj 
```
const UpdateWorkflow = DefineWorkflow({
  callback_id: "update_workflow",
  title: "Update fields",
  description: "Update fields",
  input_parameters: {
    properties: {
      interactivity: {
        type: Schema.slack.types.interactivity,
      },
      channel: {
        type: Schema.slack.types.channel_id,
      },
    },
    required: ["interactivity", "channel"],
  },
});
```
The interactivity object is passed to the workflow input from manifest.

This calls the first function:
```
const fetchFieldsFunction = UpdateWorkflow.addStep(FetchFields, {
  channelId: UpdateWorkflow.inputs.channel,
  interactivity: UpdateWorkflow.inputs.interactivity,
});
```
All this function does is get reposnse from an api call and pas it out via output params like this
```return {
        outputs: {
          fields: response,
          interactivity: inputs.interactivity,
        },
      };
```

Now comes the second function:
```
UpdateWorkflow.addStep(UpdateFields, {
  FieldData: fetchFieldsFunction.outputs.fields,
  interactivity: fetchFieldsFunction.outputs.interactivity,
  channelId: UpdateWorkflow.inputs.channel,
});
```
This second function uses this data and the interactivity pointer that it gets from first function to create a modal. Now sometimes the first function takes time to fetch the data so this gives rise to two issues:
- The interactivity pointer becomes expired, which I believe is expected. I remember in old views.open function/api call as well there is a 3s timeout.
- The user has to wait blank after pressing the workflow button for the modal to open up.

As an alternative what I am trying to do is following:
- When the user initiates the worklow the first function that is ```FetchFields``` will immidietely open a modal using client.views.open. It will contain some message "Fetching data from service"
- Once data is fetched it will pass the view.id string out in its output parameters.
- The second function will get this view.id and it will simply update the modal using
```
views.update({
  view_id: view_id,
  view: view
})
and then the remain user interaction follows.
Now when I try this out both the first and second function fail with parameter validation error.

**Comment by WilliamBergamin** [comment]
I think this may be caused by the completion of the function that is opening the modal 🤔

A more stable solution could use the following series of steps
1. Collect the data
2. Send a message with button that informs the user that form is ready to be opened
3. On button click open the model with the data from step 1
4. continue with other steps

@djmgit let me know what you think

**Comment by djmgit** [comment]
@WilliamBergamin 
Thing is that would change the flow and make it two step. Even in our current processes which are initiated by slash commands and which take slightly longer sometimes we usually go this modal route that I mentioned above that is open a modal with heads up and then show the data. Eventually these slash commands will also be moved to workflows with deno functions as shortlinks on canvas. Also its not like the data fetch takes very long otherwise the method you suggested would have been the preferred one. Its only sometimes that it crosses the 3s (I believe its still 3s in canvas as well) mark and the expired pointer thing happens since slack is extremely strict with this. I want to keep the interaction have as much less hops as possible.

**Comment by WilliamBergamin** [comment]
I see, your use case seems to fall into a gap, Slack established a 3 second restriction on interactive activities in oder to ensure a "good" UI experience for users. Our recommended solution is to break down long interactions into separate user actions (trigger the workflow, press a button to open a populated form)

You could try to merge both steps into one, where the data is collected and a form is immediately opened with [views.open](https://api.slack.com/methods/views.open), this could remove the overhead of completing one step and starting another

**Comment by djmgit** [comment]
@WilliamBergamin 
> You could try to merge both steps into one, where the data is collected and a form is immediately opened with [views.open](https://api.slack.com/methods/views.open), this could remove the overhead of completing one step and starting another

**Comment by djmgit** [comment]
@WilliamBergamin 
>You could try to merge both steps into one, where the data is collected and a form is immediately opened with [views.open](https://api.slack.com/methods/views.open), this could remove the overhead of completing one step and starting another

**Comment by djmgit** [comment]
@WilliamBergamin 
> You could try to merge both steps into one, where the data is collected and a form is immediately opened with [views.open](https://api.slack.com/methods/views.open), this could remove the overhead of completing one step and starting another

There is another problem with this. How do I pass the api response between handlers? as in from from the function that opens the modal to the ```addViewSubmissionHandler``` handler? I need some of the data from the response. I cant put it into the private_metadata because its above 3001 characters, I know the data is big but its not affecting the experience since its coming from inmemory cache. With different steps, the data would remain in ```input``` which could be accessed from any handler.

**Comment by WilliamBergamin** [comment]
For this you could take advantage of [Datastores](https://api.slack.com/automation/datastores) they are a Slack-hosted way to store data for your workflow apps

You could use the `function_execution_id`, `user_id` or any other unique identifier to store and retrieve this data between your various handlers

**Comment by djmgit** [comment]
@WilliamBergamin yeah, Datastores was like my last resort 😅 . I wanted to make sure I am not missing any simpler way.

**Comment by djmgit** [comment]
@WilliamBergamin I think you can close this issue now.
One last thing, is that not allowing of opening modal in one function and moving on to next step function a bug or a feature. IMO even if its a legit thing, there should be a better error message and not just parameter validation error. It took me sometime to pin it down because I made sure all the parameters and types are correct.
