### ISSUE TITLE
[BUG] SlackFunction interaction with buttons stops working after returning outputs, despite completed: false

### ISSUE THREAD

**Issue by tzuo9** [slackapi/deno-slack-sdk#365]
**The `deno-slack` versions**

    "deno-slack-sdk/": "https://deno.land/x/deno_slack_sdk@2.14.2/",
    "deno-slack-api/": "https://deno.land/x/deno_slack_api@2.8.0/",

**Deno runtime version**

deno 1.45.2 (release, aarch64-apple-darwin)
v8 12.7.224.12
typescript 5.5.2

**OS info**

ProductName:            macOS
ProductVersion:         14.6.1
BuildVersion:           23G93
Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:30 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6030

**Describe the bug**

Here’s a bug report based on the issue you’re facing and your code:

Title:
SlackFunction interaction with buttons stops working after returning outputs, despite completed: false

The deno-slack versions

css
Copy code
deno-slack-sdk@2.14.2
Deno runtime version

Copy code
deno 1.34.3
v8 11.2.214.10
typescript 5.1.6
OS info

yaml
Copy code
ProductName:    macOS
ProductVersion: 13.5.1
BuildVersion:   22G90
Darwin Kernel Version 23.6.0: Fri Aug 25 17:54:39 PDT 2023; root:xnu-9339.140.14~6/RELEASE_ARM64_T8103
Describe the bug

I am using SlackFunction to post an ephemeral message with buttons. Previously, when returning { completed: false } from the main function, the button interactions would continue working as expected. However, starting around two weeks ago, without any changes to my code, the interaction now ends immediately upon returning, regardless of whether I return completed: true or completed: false. As a result, the buttons no longer work after the initial return.

If I do not include a return statement, the buttons will work temporarily but eventually throw the following error causing function to fail:
`error: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'completed')
  const { completed = true, outputs = {}, error } = await functionModule
          ^
    at Object.RunFunction [as function_executed] (https://deno.land/x/deno_slack_runtime@1.1.2/run-function.ts:28:11)
    at eventLoopTick (ext:core/01_core.js:168:7)
    at async DispatchPayload (https://deno.land/x/deno_slack_runtime@1.1.2/dispatch-payload.ts:79:12)
    at async runLocally (https://deno.land/x/deno_slack_runtime@1.1.2/local-run-function.ts:36:16)
    at async https://deno.land/x/deno_slack_runtime@1.1.2/local-run-function.ts:55:3
2024-10-04 10:47:17 [error] [Fn07PK9XBQBY] (Trace=Tr07QUTJBPFB) Function 'post ephemeral response' (app function) failed
        event_dispatch_failed
`

**Steps to reproduce**

1. Define a Slack function that returns { completed: false }.
2. Deploy the function and post an ephemeral message with buttons.
3. Click the button to trigger the interaction.
4. Observe that the function completes immediately, and the button no longer functions.
5. Remove the return statement and click the button.
6. Notice that the button works for a while but eventually fails with the TypeError mentioned above.
7. source code:

```
import { DefineFunction, Schema, SlackFunction } from 'deno-slack-sdk/mod.ts';

export const postEmphemeralResponseFunction = DefineFunction({
  callback_id: 'post_emphemeral_response',
  title: 'post emphemeral response',
  description: 'Function to handle adding and not adding actions',
  source_file: 'functions/post_emphemeral_response.ts',
  input_parameters: {
    properties: {
      channel_id: {
        type: Schema.slack.types.channel_id,
        description: 'Channel where the message will be posted',
      },
      user_id: {
        type: Schema.slack.types.user_id,
        description: 'user to whom the message should be sent',
      },
      message_text: {
        type: Schema.types.string,
        description: 'Text of the message to be sent or updated',
      },
      message_ts: {
        type: Schema.types.string,
        description: 'Timestamp of the original message',
      },
      thread_ts: {
        type: Schema.types.string,
        description: 'Timestamp of the thread message',
      },
    },
    required: ['channel_id', 'user_id', 'message_text', 'message_ts'],
  },
  output_parameters: {
    properties: {
      completed: {
        type: Schema.types.boolean,
        description: 'Indicates if the function completed successfully',
      },
      message: {
        type: Schema.types.string,
        description: 'A confirmation message or result of the action',
      },
    },
    required: ['completed'],
  },
});

export default SlackFunction(
  postEmphemeralResponseFunction,
  async ({ inputs, client }) => {
    console.log('[PostEmphemeralResponseFunction] Received inputs:', inputs);  
    const blocks = [
      {
          type: "section",
          text: {
            type: "mrkdwn",
            text: inputs.message_text,
          },
      },
      {
      "type": "actions",
      "block_id": `post_sgp_response`,
      "elements": [
        {
          type: "button",
          text: {
            type: "plain_text",
            text: "Post",
          },
          action_id: `post_action`,
          style: "primary",
        },
      ],
    }];
    console.log('[PostEmphemeralResponseFunction] Posting ephemeral message');
    console.log('[PostEmphemeralResponseFunction] thread_ts:', inputs.thread_ts, 'message_ts:', inputs.message_ts, 'is_reply:', inputs.thread_ts != inputs.message_ts);


  if (inputs.thread_ts) {
    // If thread_ts is present -> user asks in thread, post the ephemeral message in the thread
    await client.chat.postEphemeral({
      channel: inputs.channel_id,
      user: inputs.user_id,
      blocks,
      thread_ts: inputs.message_ts,
    });
  } else {
    // If thread_ts is not present -> user asks in main channel, post the ephemeral message in the main channel
    await client.chat.postEphemeral({
      channel: inputs.channel_id,
      user: inputs.user_id,
      blocks,
    });
  }
  return {
    outputs: {
      completed: false,
    },
  }
  },
).addBlockActionsHandler(
  'post_action',
  async function ({ body, client, inputs }) {
    const postResponse = await client.chat.postMessage({
      channel: body.container.channel_id,
      thread_ts: inputs.message_ts,
      text: inputs.message_text,
    });   
    console.log('[PostEmphemeralResponseFunction] Posting message at channel:', body.container.channel_id, 'with ts:', inputs.thread_ts);
    return {
      outputs: {
        completed: true,
        message: "Actions completed!",
      },
    }
  },
);
```

**Expected result**

When { completed: false } is returned, the function should continue, allowing subsequent button interactions without completing the workflow.
 
**Actual result**

The function completes immediately upon returning, and the buttons do not work as expected.
If no return statement is included, the button interactions work for a short while before failing with a TypeError.

**Requirements**

Please read the [Contributing guidelines](https://github.com/slackapi/deno-slack-sdk/blob/main/.github/contributing.md) and [Code of Conduct](https://slackhq.github.io/code-of-conduct) before creating this issue or pull request. By submitting, you are agreeing to those rules.

**Comment by hello-ashleyintech** [comment]
Hi, @tzuo9! Thanks for submitting this 🙌 So sorry for the trouble you're encountering!

I'm going to try to repro and also check with our Deno SDK team to see if they have any ideas about what could've caused this sudden change.

**Comment by filmaj** [comment]
@tzuo9 I believe you have a bug in your code. The return statement for your function handlers are incorrect:

```typescript
  return {
    outputs: {
      completed: false,
    },
  }
```

Please see the bottom of [the Custom Function context documentation](https://api.slack.com/automation/functions/custom#context) for the correct structure of the `return` object. I believe you want:

```typescript
  return {
    completed: false,
  }
```

Your `addBlockActionsHandler` return object is also similarly incorrect.

I have a feature-rich interactivity example app that you can use as a working example [here](https://github.com/filmaj/interactive-approval/blob/main/functions/approval/mod.ts#L37-L40).

**Comment by tzuo9** [comment]
@filmaj yes that works thank you so much!
