### ISSUE TITLE
[FEATURE] Increase outgoingDomains limit

### ISSUE THREAD

**Issue by benjrich-jasper** [slackapi/deno-slack-sdk#368]
**Description of the problem being solved**
We have been bumping into the limit of 10 domains in the `outgoingDomains` section for a while now. Luckily, every time we've hit it, there's been one we could remove, but it's looking like we're going to keep our current 10 for the foreseeable future. 

Can we get the limit increased to something like `20` or just remove the limit alltogether?

Manifest example here:
```
export default Manifest({
    name: "test-app"
    outgoingDomains: [
        "example.com",
        "example.com",
        "example.com",
        "example.com",
        "example.com",
        "example.com",
        "example.com",
        "example.com",
        "example.com",
    ]
})
```

**Comment by filmaj** [comment]
Following up with the hosting team on this one, will let you know what I find!

**Comment by filmaj** [comment]
I have a change up for review that bumps this limit from 10 to 100, FYI. Will report back once that's released.

**Comment by filmaj** [comment]
I believe this should now be resolved as the limit has been bumped to 100 in production! Closing this, but feel free to reopen/comment/open a new issue if you are having trouble with this.

**Comment by benjrich-jasper** [comment]
Awesome! Thanks for always coming in clutch and fixing everything!
