### ISSUE TITLE
Issue with Slack deploy on Windows machine - Slack run works fine

### ISSUE THREAD

**Issue by Sahilacharya48** [slackapi/deno-slack-sdk#391]
I've been trying to deploy a Slack Next Gen App to my workspace and I've tested that using Slack Run and that seems to be working as expected. But when I use Slack deploy, it shows Packaging issues (sharing the error below).

FYI - I've already deployed this same app to another workspace using Mac and that worked fine without any issues. 
Looking at the issue I found these similar one #258 and I cleared up just about everything from function.ts just to see if there is any code issues or something else but issue still persists somehow.

 Packaging app for deploymentX [ERROR] Could not resolve "\\Slack Apps\\slack_store_messages\\functions\\slackstoremessage_function.ts" [plugin deno-resolver]
  The plugin "deno-resolver" didn't set a resolve directory, so esbuild did not search for "\\Slack Apps\\slack_store_messages\\functions\\slackstoremessage_function.ts" on the file system.
Error bundling function file "apicall" with esbuild
error: Uncaught (in promise) Error: Build failed with 1 error:
error: Could not resolve "\\Slack Apps\\slack_store_messages\\functions\\slackstoremessage_function.ts"
  let error = new Error(text);
              ^
    at failureErrorWithLog (https://deno.land/x/esbuild@v0.19.4/mod.js:1626:15)
    at https://deno.land/x/esbuild@v0.19.4/mod.js:1035:25
    at runOnEndCallbacks (https://deno.land/x/esbuild@v0.19.4/mod.js:1461:45)
    at buildResponseToResult (https://deno.land/x/esbuild@v0.19.4/mod.js:1033:7)
    at https://deno.land/x/esbuild@v0.19.4/mod.js:1062:16
    at responseCallbacks.<computed> (https://deno.land/x/esbuild@v0.19.4/mod.js:679:9)
    at handleIncomingPacket (https://deno.land/x/esbuild@v0.19.4/mod.js:739:9)
    at readFromStdout (https://deno.land/x/esbuild@v0.19.4/mod.js:655:7)
    at https://deno.land/x/esbuild@v0.19.4/mod.js:1924:11
    at eventLoopTick (ext:core/01_core.js:175:7)
Packaging app for deployment
Check C:\Users\<--User-->\.slack\logs\slack-debug-20241212.log for error logs
error packaging project: Command for 'BuildProject' returned an error: exit status 1 (sdk_hook_invocation_failed)

> Suggestion
   Run `slack doctor` to check that your system dependencies are up-to-date.
   
   SYSTEM

    ✔ Operating System (system management software)
        Version: windows (amd64)

    ✔ Git (a version control system)
        Version: git version 2.47.1.windows.1

SLACK

    ✔ CLI (this tool for building Slack apps)
        Version: 2.31.0

    ✔ Configurations (any adjustments to settings)
        System ID: ####
        Last updated: 2024-12-11 09:47:35 Z
        Experiments: None

    ✔ Credentials (your Slack authentication)
        Team domain: ####
        Team ID: ####
        User ID: ####
        Last updated: 2024-12-12 13:26:15 +05:30
        Authorization level: Workspace
        Token status: Valid

PROJECT

    ✔ Configurations (your project's CLI settings)
        Project ID: ####

    ✔ Runtime (foundations for the application)
        deno: 2.1.1
        Note: Applications deployed to Slack use Deno version 1.46.2

        typescript: 5.6.2
        v8: 13.0.245.12-rusty

    ✔ Dependencies (requisites for development)
        deno_slack_hooks: 1.3.1
        deno_slack_sdk: 2.14.2
        deno_slack_api: 2.8.0

Errors: 0

> We would love to know how things are going
   Survey your development experience with slack feedback --name platform-improvements

**Comment by zimeg** [comment]
@Sahilacharya48 oh darn... My next guess would be from changes to bundling appearing with `deno` 2. Can you try deploying with `deno` 1.46.2?

```sh
deno upgrade --version 1.46.2
```

**Comment by Sahilacharya48** [comment]
Wow. That worked like magic. Changing the version to 1.46.2 made the build successfully and deployment worked. 
Thank you! @zimeg 
So is it like a known issue? If in future lets say the minimum deno version required is 2, would I be getting this again? Just curious.

**Comment by zimeg** [comment]
@Sahilacharya48 Sweet, this is great to hear! Thanks for experimenting with all of this! 🙏

We've noticed that `deploy` on Windows fails more often than Linux #316 and our current recommendation is to try WSL if changing the `deno` version doesn't work.

As for updates with `deno` 2 - we have no immediate timeline for this but a `deploy` error like this would be an unexpected **bug** if it was to return 🐛  Of course, we'd hope to not introduce such a regression in that change, but also appreciate when issues are opened so we can investigate! 🔍

**Comment by zimeg** [comment]
@Sahilacharya48 I'm also going to close this issue, but please feel free to follow up if you're running into other issues! 🚀

**Comment by wake0up0ne0** [comment]
For me it was failng to delpoy even example code like [this](https://github.com/slack-samples/deno-reverse-string).
Latest Win 11, latest dino and Slack CLI version. 
Had to do deno downgrade as advised by @zimeg 
Thank you!
