### ISSUE TITLE
Fix WorkflowParameterReferences type to not have optional properties

### ISSUE THREAD

**Issue by selfcontained** [slackapi/deno-slack-sdk#48]
The `WorkflowParameterReferences` type is what's used for referencing Workflow inputs, and step outputs when using `DefineWorkflow()` and adding steps. If I have an optional input parameter on my workflow:

```ts
const workflow = DefineWorkflow({
  callback_id: "my_workflow",
  title: "Blah",
  input_parameters: {
    properties: {
      name: {
        type: "string",
      },
    },
    required: [],
  },
});
```

And then try and reference the input on that workflow (which is useful when assigning it as the input of a step), it treats it as optional, but in reality, these are parameter references that are always present when defining workflows, it's just the runtime value that may be optional.

```ts
workflow.inputs.name
```
<img width="264" alt="image" src="https://user-images.githubusercontent.com/367275/177429662-9afa988c-1761-4c0a-8dca-838d9f441850.png">

If we adjust the `WorkflowParameterReferences` (defined [here](https://github.com/slackapi/deno-slack-sdk/blob/main/src/workflows/types.ts#L56-L67)) so that it doesn't try to distinguish required/optional params that would fix it. For example, it could just be:

```ts
type WorkflowParameterReferences<
  Parameters extends ParameterSetDefinition,
> = {
  [name in keyof Parameters]: ParameterVariableType<Parameters[name]>;
};
```

We would need to update a few references to it that are passing in a second generic argument, and wrap some tests around it too if we can.

**Comment by shapirone** [comment]
Fixed in #124
